{
 "title": "SpeedTest Monitor",
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, (download_speed * 8 / 1000000.0) AS \"Download\" FROM speedtest_results ORDER BY timestamp;"
    },
    {
     "rawSql": "SELECT timestamp, (upload_speed * 8 / 1000000.0) AS \"Upload\" FROM speedtest_results ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Download (Mbps)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT (download_speed * 8 / 1000000.0) AS \"Download\" FROM speedtest_results; "
    }
   ]
  },
  {
   "title": "Upload (Mbps)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT (upload_speed * 8 / 1000000.0) AS \"Upload\" FROM speedtest_results;"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, latency AS \"Latency\" FROM speedtest_results ORDER BY timestamp;"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', timestamp) as time,\n  AVG(download_speed * 8 / 1000000.0) as value\nFROM speedtest_results\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  }
 ]
}